name: 'Generate and deploy'

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  check-and-deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Check for new non-draft content
        id: check_content
        run: |
          echo "Checking changed files..."
          DEPLOY="false"
          
          # List all changed files
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt
          
          # Check content files
          while IFS= read -r file; do
            if [[ $file == content/* ]] && [ -f "$file" ]; then
              echo "Checking file: $file"
              if ! grep -q "draft: true" "$file"; then
                echo "Found non-draft content in $file"
                DEPLOY="true"
                break
              fi
            fi
          done < changed_files.txt
          
          echo "deploy=$DEPLOY" >> $GITHUB_OUTPUT
          echo "Deploy status: $DEPLOY"

      - name: Generate and deploy website
        if: steps.check_content.outputs.deploy == 'true' || github.event_name == 'workflow_dispatch'
        uses: evnmrk/hugo-rsync-deployment@master
        env:
          VPS_DEPLOY_KEY: ${{ secrets.VPS_DEPLOY_KEY }}
          VPS_DEPLOY_USER: ${{ secrets.SSH_USER }}
          VPS_DEPLOY_HOST: evnmrk.xyz
          VPS_DEPLOY_DEST: /var/www/mysite/
        with:
          hugo-arguments: '--minify'
          rsync-arguments: '--archive --compress --xattrs --delete'
