name: 'Generate and deploy'

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  check-and-deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Debug git info
        run: |
          echo "Current commit: $(git rev-parse HEAD)"
          echo "Previous commit: ${{ github.event.before }}"
          echo "All changed files:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}

      - name: Check for new non-draft content
        id: check_content
        run: |
          echo "Starting content check..."
          
          # Create a list of changed content files
          CHANGED_CONTENT=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^content/.*\.md$" || true)
          
          if [ -z "$CHANGED_CONTENT" ]; then
            echo "No content files were changed"
            echo "deploy=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          echo "Changed content files:"
          echo "$CHANGED_CONTENT"
          
          # Check each changed content file
          while IFS= read -r file; do
            if [ -f "$file" ]; then
              echo "Checking file: $file"
              echo "File contents:"
              cat "$file"
              
              if ! grep -q "draft: true" "$file"; then
                echo "Found non-draft content in $file"
                echo "deploy=true" >> $GITHUB_OUTPUT
                exit 0
              fi
            fi
          done <<< "$CHANGED_CONTENT"
          
          echo "No non-draft content found"
          echo "deploy=false" >> $GITHUB_OUTPUT

      - name: Generate and deploy website
        if: steps.check_content.outputs.deploy == 'true' || github.event_name == 'workflow_dispatch'
        uses: evnmrk/hugo-rsync-deployment@master
        env:
          VPS_DEPLOY_KEY: ${{ secrets.VPS_DEPLOY_KEY }}
          VPS_DEPLOY_USER: ${{ secrets.SSH_USER }}
          VPS_DEPLOY_HOST: evnmrk.xyz
          VPS_DEPLOY_DEST: /var/www/mysite/
        with:
          hugo-arguments: '--minify'
          rsync-arguments: '--archive --compress --xattrs --delete'
